export const ADD = "ADD";
export const BUY_COCA = "BUY_COCA";
export const DEC = "DEC";
export const FETCH_POST_REQUEST = "FETCH_POST_REQUEST";
export const FETCH_POST_SUCCESS = "FETCH_POST_SUCCESS";
export const FETCH_POST_FAILD = "FETCH_POST_FAILD";
export const FULLNAME = "FULLNAME";
export const CLEARNAME = "CLEARNAME";
export const FETCH_USERS_REQUESET = "FETCH_USER_REQUESET";
export const FETCH_USERS_SUCCESS = "FETCH_USER_SUCCESS";
export const FETCH_USERS_ERROR = "FETCH_USER_ERROR";


